# Generated by Django 4.1.5 on 2023-01-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardjob',
            name='job_posting',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
